.\" Manpage for electrotest-standalone.
.TH man 1 "5 January 2020"
.SH NAME
electrotest-standalone \- Calculate effect and resistances in an electric circuit
.SH SYNOPSIS
electrotest-standalone
.SH DESCRIPTION
electrotest-standalone asks you to describe the electric circuit, and then calculates the effect, and which 3 resistors from the E12 series that can replace this circuit.
.SH BUGS
I'm sure there are loads.
